#!/bin/bash
server=http://ammarkov.ath.cx
target=$server/myloader
echo "Uploading to $target"
pattern="$target/file.php\?i=[a-z0-9]*-$1"
curl -F uploadedfile=@$1 -F rawresponse=YES -F submit="Upload File" $target/index.php | egrep -o $pattern
exit 0
