#!/usr/local/bin/bash

path="/home/ammar/public_html/atech/uploads/uploads/"

for dire in $(ls -F $path | grep \/); do
if [ `ls -ld $path$dire | cut -d' ' -f11` != `date | cut -d' ' -f4` ]; then
rm -rf $path$dire
fi
done

exit 0


